sudo: true
language: python
matrix:
  include:
  - os: linux
    python: "2.7"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9', 'gcc-7', 'g++-7']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=2.7
  - os: linux
    python: "3.4"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9', 'gcc-7', 'g++-7']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.4
  - os: linux
    python: "3.5"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9', 'gcc-7', 'g++-7']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.5
  - os: linux
    python: "3.6"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9', 'gcc-7', 'g++-7']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.6

install:
  - if [ "${PYTHON:0:1}" = "3" ]; then export PY=3; fi
  - pip$PY install --upgrade pip setuptools wheel
  - pip$PY install --only-binary=numpy,scipy numpy scipy
  - pip$PY install -r requirements.txt
  - pip$PY install pytest-cov
  - pip$PY install coveralls
  - CC=g++-7 pip$PY install revkit
  - if [ "${PYTHON:0:1}" = "3" ]; then pip$PY install dormouse; fi
  - cd ../.. && git clone https://github.com/vm6502q/qrack.git
  - cd qrack && mkdir _build && cd _build && cmake .. -DENABLE_COMPLEX8=OFF && sudo make install && cd ../.. && sudo rm -r qrack && cd ProjectQ-Framework/ProjectQ
  - pip$PY install -e . --global-option="--with-qracksimulator"

# command to run tests
script: export OMP_NUM_THREADS=1 && pytest projectq --cov projectq

after_success:
  - coveralls
